blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/eybNUqD8gf
    about: Join our Discord server for support and community discussion.
  - name: ðŸ“– Documentation
    url: https://ls1intum.github.io/prompt2/
    about: Explore the official PROMPT 2 documentation.
