basePath: /template-service/api
definitions:
  promptTypes.PhaseCopyRequest:
    properties:
      sourceCoursePhaseID:
        description: |-
          SourceCoursePhaseID is the unique identifier of the course phase to copy from.
          This phase serves as the template and its data will be duplicated.
        type: string
      targetCoursePhaseID:
        description: |-
          TargetCoursePhaseID is the unique identifier of the course phase to copy into.
          This phase will receive the copied data and configurations.
        type: string
    type: object
externalDocs:
  description: PROMPT Documentation
  url: https://ls1intum.github.io/prompt2/
host: localhost:8086
info:
  contact: {}
  description: This is the template server of PROMPT.
  title: PROMPT Template API
  version: "1.0"
paths:
  /copy:
    post:
      consumes:
      - application/json
      description: Copy template server data from a source course phase to a target
        course phase.
      parameters:
      - description: Copy request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/promptTypes.PhaseCopyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Copy course phase data
      tags:
      - copy
  /course_phase/{coursePhaseID}/config:
    get:
      description: Get configuration status flags for a course phase.
      parameters:
      - description: Course Phase UUID
        in: path
        name: coursePhaseID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get phase configuration status
      tags:
      - config
  /course_phase/{coursePhaseID}/hello:
    get:
      description: Returns a simple hello message from the template server.
      parameters:
      - description: Course Phase UUID
        in: path
        name: coursePhaseID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Template server health check
      tags:
      - template
  /course_phase/{coursePhaseID}/info:
    get:
      description: Get template-specific info for a course phase.
      parameters:
      - description: Course Phase UUID
        in: path
        name: coursePhaseID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get template info
      tags:
      - template
swagger: "2.0"
